### ISSUE TITLE
Tapping “Copy Code” should use a callback URL to also open discord

### ISSUE THREAD

**Issue by mvanormer** [Lovely-Development-Team/Elsewhen#13]
Alternatively, a second button (“Copy and Open Discord”) should be added below the existing button

**Comment by benbacardi** [comment]
@mvanormer Do you know a URL that'll open the Discord app? I'm struggling to find one.

**Comment by alexcfaber** [comment]
As far as I know there isn't an officially supported way at the moment. Supposedly discord://discordapp.com worked for some people for a while.

**Comment by benbacardi** [comment]
Closing as this seems basically impossible to do??
